export const arrayImages = ["../../../images/Avatars/1.jpg", "../../../images/Avatars/2.jpg", "../../../images/Avatars/3.jpg", "../../../images/Avatars/4.jpg", "../../../images/Avatars/5.jpg",
"../../../images/Avatars/aiony-haust-3TLl_97HNJo-unsplash.jpg", "../../../images/Avatars/alex-suprun-UUp9z94QhLA-unsplash.jpg", "../../../images/Avatars/andrew-power-9ZXpKFlQkjo-unsplash.jpg", 
"../../../images/Avatars/brandon-zacharias-ITo4f_z3wNM-unsplash.jpg", "../../../images/Avatars/diego-hernandez-MSepzbKFz10-unsplash.jpg", "../../../images/Avatars/edward-cisneros-_H6wpor9mjs-unsplash.jpg",
"../../../images/Avatars/fatane-rahimi-GNpmCi26fpI-unsplash.jpg", "../../../images/Avatars/foto-sushi-6anudmpILw4-unsplash.jpg", "../../../images/Avatars/foto-sushi-ExVlW9b648Q-unsplash.jpg", "../../../images/Avatars/foto-sushi-JgXxNIHotZ8-unsplash.jpg",
"../../../images/Avatars/foto-sushi-ocOW8-uiAjk-unsplash.jpg", "../../../images/Avatars/giorgio-encinas-n34dhlh0spw-unsplash.jpg", "../../../images/Avatars/jake-nackos-IF9TK5Uy-KI-unsplash.jpg", "../../../images/Avatars/joseph-gonzalez-iFgRcqHznqg-unsplash.jpg",
"../../../images/Avatars/julian-wan-2EdIX-O2lkI-unsplash.jpg", "../../../images/Avatars/jurica-koletic-7YVZYZeITc8-unsplash.jpg", "../../../images/Avatars/leilani-angel-K84vnnzxmTQ-unsplash.jpg", "../../../images/Avatars/leio-mclaren-L2dTmhQzx4Q-unsplash.jpg", "../../../images/Avatars/luis-villasmil-6qf1uljGpU4-unsplash.jpg",
"../../../images/Avatars/luis-villasmil-Z4rqvRpRj38-unsplash.jpg", "../../../images/Avatars/michael-dam-mEZ3PoFGs_k-unsplash.jpg", "../../../images/Avatars/nicolas-horn-MTZTGvDsHFY-unsplash.jpg", "../../../images/Avatars/nicolas-horn-MTZTGvDsHFY-unsplash.jpg", "../../../images/Avatars/olga-nayda-fHXpgMd_XhE-unsplash.jpg",
"../../../images/Avatars/olga-nayda-qmfietKZbm0-unsplash.jpg", "../../../images/Avatars/shubham-mourya-j8TvjpdQzzI-unsplash.jpg", "../../../images/Avatars/sigmund-jzz_3jWMzHA-unsplash.jpg", "../../../images/Avatars/taras-shypka-QEgHL8NN7nM-unsplash.jpg",
"../../../images/Avatars/vicky-hladynets-C8Ta0gwPbQg-unsplash.jpg", "../../../images/Avatars/viktor-kirichenko-nEOSQiA_FHc-unsplash.jpg", "../../../images/Avatars/vitaliy-gavrushchenko-wlj_fNCAsJk-unsplash.jpg",];
